# Application
spring.application.name=java-marketplace

# Load environment variables from .env (parsed as a properties file)
# spring.config.import=optional:file:.env[.properties]
spring.config.import=file:.env[.properties]

# HTTP
scalar.url=/v3/api-docs
scalar.path=/scalar
springdoc.swagger-ui.syntax-highlight.theme=obsidian
springdoc.paths-to-exclude=/scalar/**, /scalar

# HTTP - JWT
security.token.secret=${JWT_SECRET}
security.token.roles-claim=roles
security.token.issuer=java-marketplace
security.token.access-ttl=PT15M

# Database
spring.datasource.url=jdbc:postgresql://${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate